# Generated by Django 2.1.7 on 2019-03-19 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0006_asistente'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultorio',
            name='Direccion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Direccion'),
        ),
    ]
