# Generated by Django 2.1.7 on 2019-03-19 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0007_consultorio_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='Facturacion_datos_paciente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Facturacion_datos_paciente'),
        ),
    ]
