# Generated by Django 2.1.7 on 2019-03-19 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0009_paciente_expediente'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Paciente'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='Alergia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Alergia'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='Antecedentes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Antecedentes'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='Direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Direccion'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='Telefono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Telefono'),
        ),
    ]
