# Generated by Django 2.1.7 on 2019-03-19 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0013_doctor_asistente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contraseña',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contraseña', models.CharField(max_length=45)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Password',
        ),
        migrations.AddField(
            model_name='paciente',
            name='Acompañante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Acompañante'),
        ),
        migrations.DeleteModel(
            name='Password',
        ),
        migrations.AddField(
            model_name='doctor',
            name='Contraseña',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Contraseña'),
        ),
    ]
