# Generated by Django 2.1.7 on 2019-03-20 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0017_consulta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consulta_conf',
            new_name='Consulta_campos_conf',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='Consulta_conf',
            new_name='Consulta_campos_conf',
        ),
    ]
