# Generated by Django 2.1.7 on 2019-03-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0018_auto_20190320_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta_campos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=45)),
                ('tipo', models.CharField(max_length=45)),
                ('sub_tipo', models.CharField(max_length=45)),
                ('tipo_campo', models.CharField(max_length=4)),
                ('nota', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=4)),
                ('nombre_diagnostico', models.CharField(max_length=200)),
                ('vigente', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_carpeta', models.CharField(max_length=90)),
                ('fecha_estudios', models.DateField()),
                ('url_archivo', models.CharField(max_length=90)),
            ],
        ),
    ]
