# Generated by Django 2.1.7 on 2019-03-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0019_consulta_campos_diagnostico_estudio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=200)),
                ('indicaciones', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('descripcion_pago', models.CharField(max_length=200)),
                ('monto', models.IntegerField()),
                ('forma_pago', models.CharField(max_length=4)),
                ('factura_pago', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_receta', models.DateField()),
                ('folio_receta', models.CharField(max_length=20)),
            ],
        ),
    ]
