# Generated by Django 2.1.7 on 2019-03-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0026_auto_20190322_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_personales',
            name='fecha_nacimiento',
            field=models.DateField(blank=True),
        ),
    ]
