# Generated by Django 2.1.7 on 2019-03-25 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0037_auto_20190322_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acompañante',
            name='Datos_personales',
        ),
        migrations.RemoveField(
            model_name='acompañante',
            name='Direccion',
        ),
        migrations.RemoveField(
            model_name='acompañante',
            name='Telefono',
        ),
        migrations.RemoveField(
            model_name='asistente',
            name='Contraseña',
        ),
        migrations.RemoveField(
            model_name='asistente',
            name='Datos_personales',
        ),
        migrations.RemoveField(
            model_name='asistente',
            name='Direccion',
        ),
        migrations.RemoveField(
            model_name='asistente',
            name='Telefono',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='Consulta_campos',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='Diagnostico',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='Estudio',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='Pago',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='Receta',
        ),
        migrations.RemoveField(
            model_name='consultorio',
            name='Direccion',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Asistente',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Cita_externa',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Consulta_campos_conf',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Consultorio',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Contraseña',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Datos_personales',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Direccion',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Especialidad',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Expediente_conf',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Facturacion_datos_doctor',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Horario',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Paciente',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Servicio_externo',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Telefono',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='Acompañante',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='Alergia',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='Antecedentes',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='Consulta',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='Datos_personales',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='Direccion',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='Expediente',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='Facturacion_datos_paciente',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='Telefono',
        ),
        migrations.AddField(
            model_name='acompañante',
            name='Paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Paciente'),
        ),
        migrations.AddField(
            model_name='alergia',
            name='Paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Paciente'),
        ),
        migrations.AddField(
            model_name='antecedentes',
            name='Paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Paciente'),
        ),
        migrations.AddField(
            model_name='asistente',
            name='Doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Doctor'),
        ),
        migrations.AddField(
            model_name='cita_externa',
            name='Doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Doctor'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='Paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Paciente'),
        ),
        migrations.AddField(
            model_name='consulta_campos',
            name='Consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Consulta'),
        ),
        migrations.AddField(
            model_name='consulta_campos_conf',
            name='Doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Doctor'),
        ),
        migrations.AddField(
            model_name='consultorio',
            name='Doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Doctor'),
        ),
        migrations.AddField(
            model_name='contraseña',
            name='Asistente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Asistente'),
        ),
        migrations.AddField(
            model_name='contraseña',
            name='Doctor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Doctor'),
        ),
        migrations.AddField(
            model_name='datos_personales',
            name='Acompañante',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Acompañante'),
        ),
        migrations.AddField(
            model_name='datos_personales',
            name='Asistente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Asistente'),
        ),
        migrations.AddField(
            model_name='datos_personales',
            name='Doctor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Doctor'),
        ),
        migrations.AddField(
            model_name='datos_personales',
            name='Paciente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Paciente'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='Consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Consulta'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='Acompañante',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Acompañante'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='Asistente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Asistente'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='Doctor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Doctor'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='Paciente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Paciente'),
        ),
        migrations.AddField(
            model_name='especialidad',
            name='Doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Doctor'),
        ),
        migrations.AddField(
            model_name='estudio',
            name='Consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Consulta'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='Paciente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Paciente'),
        ),
        migrations.AddField(
            model_name='expediente_conf',
            name='Doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Doctor'),
        ),
        migrations.AddField(
            model_name='facturacion_datos_doctor',
            name='Doctor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Doctor'),
        ),
        migrations.AddField(
            model_name='facturacion_datos_paciente',
            name='Paciente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Paciente'),
        ),
        migrations.AddField(
            model_name='horario',
            name='Doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Doctor'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='Doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Doctor'),
        ),
        migrations.AddField(
            model_name='pago',
            name='Consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Consulta'),
        ),
        migrations.AddField(
            model_name='pago',
            name='Servicio_externo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Servicio_externo'),
        ),
        migrations.AddField(
            model_name='receta',
            name='Consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Consulta'),
        ),
        migrations.AddField(
            model_name='servicio_externo',
            name='Doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Doctor'),
        ),
        migrations.AddField(
            model_name='telefono',
            name='Acompañante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Acompañante'),
        ),
        migrations.AddField(
            model_name='telefono',
            name='Asistente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Asistente'),
        ),
        migrations.AddField(
            model_name='telefono',
            name='Doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Doctor'),
        ),
        migrations.AddField(
            model_name='telefono',
            name='Paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Paciente'),
        ),
    ]
