# Generated by Django 2.1.7 on 2019-03-25 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0039_auto_20190325_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio_externo',
            name='Doctor',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='Servicio_externo',
        ),
        migrations.AddField(
            model_name='pago',
            name='Doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Doctor'),
        ),
        migrations.AddField(
            model_name='pago',
            name='tipo_pago',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.DeleteModel(
            name='Servicio_externo',
        ),
    ]
