# Generated by Django 2.1.7 on 2019-03-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0040_auto_20190325_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contraseña',
            name='Asistente',
        ),
        migrations.RemoveField(
            model_name='contraseña',
            name='Doctor',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='Acompañante',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='Asistente',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='Doctor',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='Paciente',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='dgp',
        ),
        migrations.AddField(
            model_name='acompañante',
            name='calle',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='acompañante',
            name='colonia',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='acompañante',
            name='cp',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='acompañante',
            name='num_exterior',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='acompañante',
            name='num_interior',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='asistente',
            name='Contraseña',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='asistente',
            name='calle',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='asistente',
            name='colonia',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='asistente',
            name='cp',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='asistente',
            name='num_exterior',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='asistente',
            name='num_interior',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Contraseña',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='calle',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='colonia',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='cp',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='num_exterior',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='num_interior',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='calle',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='colonia',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cp',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='num_exterior',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='num_interior',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Contraseña',
        ),
        migrations.DeleteModel(
            name='Direccion',
        ),
    ]
