# Generated by Django 2.1.7 on 2019-03-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0045_auto_20190327_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostico',
            name='nombre_doctor',
        ),
        migrations.RemoveField(
            model_name='diagnostico',
            name='rfc_doctor',
        ),
        migrations.AddField(
            model_name='consulta',
            name='nombre_doctor',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='rfc_doctor',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
