# Generated by Django 2.1.7 on 2019-03-27 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0047_auto_20190327_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefono_Acompañante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=3, null=True)),
                ('lada', models.CharField(max_length=3, null=True)),
                ('telefono', models.CharField(max_length=10, null=True)),
                ('Acompañante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Acompañante')),
            ],
        ),
        migrations.CreateModel(
            name='Telefono_Asistente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=3, null=True)),
                ('lada', models.CharField(max_length=3, null=True)),
                ('telefono', models.CharField(max_length=10, null=True)),
                ('Asistente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Asistente')),
            ],
        ),
        migrations.CreateModel(
            name='Telefono_Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=3, null=True)),
                ('lada', models.CharField(max_length=3, null=True)),
                ('telefono', models.CharField(max_length=10, null=True)),
                ('Doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Telefono_Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=3, null=True)),
                ('lada', models.CharField(max_length=3, null=True)),
                ('telefono', models.CharField(max_length=10, null=True)),
                ('Paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Paciente')),
            ],
        ),
    ]
