# Generated by Django 2.1.7 on 2019-03-27 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0049_auto_20190327_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefono_acompañante',
            name='Acompañante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Acompañante'),
        ),
        migrations.AlterField(
            model_name='telefono_asistente',
            name='Asistente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Asistente'),
        ),
        migrations.AlterField(
            model_name='telefono_doctor',
            name='Doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Doctor'),
        ),
        migrations.AlterField(
            model_name='telefono_paciente',
            name='Paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Paciente'),
        ),
    ]
