# Generated by Django 2.1.7 on 2019-03-27 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0051_auto_20190327_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudio',
            old_name='nombre_carpeta',
            new_name='nombre_estudio',
        ),
    ]
