# Generated by Django 2.1.7 on 2019-03-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0053_auto_20190327_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='Consulta',
        ),
        migrations.AddField(
            model_name='pago',
            name='id_consulta',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='pago_consulta',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
