# Generated by Django 2.1.7 on 2019-03-27 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0056_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
