# Generated by Django 2.1.7 on 2019-03-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0059_auto_20190327_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acompañante',
            name='correo',
            field=models.EmailField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='asistente',
            name='correo',
            field=models.EmailField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='correo',
            field=models.EmailField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='correo',
            field=models.EmailField(blank=True, max_length=45, null=True),
        ),
    ]
