# Generated by Django 2.1.7 on 2019-03-28 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0063_auto_20190328_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alergia',
            options={'verbose_name_plural': 'Pacientes - Alergias'},
        ),
        migrations.AlterModelOptions(
            name='antecedentes',
            options={'verbose_name_plural': 'Pacientes - Antecedentes'},
        ),
        migrations.AlterModelOptions(
            name='cita_externa',
            options={'verbose_name_plural': 'Doctores - Citas Externas'},
        ),
        migrations.AlterModelOptions(
            name='consulta',
            options={'verbose_name_plural': 'Pacientes - Consultas'},
        ),
        migrations.AlterModelOptions(
            name='consultorio',
            options={'verbose_name_plural': 'Doctores - Consultorios'},
        ),
        migrations.AlterModelOptions(
            name='especialidad',
            options={'verbose_name_plural': 'Doctores - Especialidades'},
        ),
        migrations.AlterModelOptions(
            name='facturacion_datos_doctor',
            options={'verbose_name_plural': 'Doctores - Datos de facturación'},
        ),
        migrations.AlterModelOptions(
            name='facturacion_datos_paciente',
            options={'verbose_name_plural': 'Pacientes - Datos de Facturación'},
        ),
        migrations.AlterModelOptions(
            name='horario',
            options={'verbose_name_plural': 'Doctores - Horarios'},
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={'verbose_name_plural': 'Doctores - Pagos'},
        ),
    ]
