# Generated by Django 2.1.7 on 2019-03-28 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0064_auto_20190328_1916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudio',
            options={'verbose_name_plural': 'Pacientes - Estudios'},
        ),
    ]
