# Generated by Django 2.1.7 on 2019-03-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0004_auto_20190319_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acompañante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relacion', models.CharField(max_length=45)),
            ],
        ),
    ]
