# Generated by Django 2.1.7 on 2019-03-19 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0008_paciente_facturacion_datos_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='Expediente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Expediente'),
        ),
    ]
