# Generated by Django 2.1.7 on 2019-03-19 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0010_auto_20190319_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='Datos_personales',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Datos_personales'),
        ),
    ]
