# Generated by Django 2.1.7 on 2019-03-19 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0011_paciente_datos_personales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='Datos_personales',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Datos_personales'),
        ),
    ]
