# Generated by Django 2.1.7 on 2019-03-19 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0012_auto_20190319_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Asistente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Asistente'),
        ),
    ]
