# Generated by Django 2.1.7 on 2019-03-20 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0021_auto_20190320_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='Consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Consulta'),
        ),
    ]
