# Generated by Django 2.1.7 on 2019-03-21 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0022_paciente_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistente',
            name='Contraseña',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Contraseña'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Contraseña',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Contraseña'),
        ),
    ]
