# Generated by Django 2.1.7 on 2019-03-21 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0023_auto_20190321_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
