# Generated by Django 2.1.7 on 2019-03-22 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0025_auto_20190322_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_personales',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='datos_personales',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='datos_personales',
            name='correo',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='datos_personales',
            name='nombre',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AlterField(
            model_name='datos_personales',
            name='rfc',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='datos_personales',
            name='sexo',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='datos_personales',
            name='url_foto',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Datos_personales',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Datos_personales'),
        ),
    ]
