# Generated by Django 2.1.7 on 2019-03-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0027_auto_20190322_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acompañante',
            name='relacion',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='proxima_consulta',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='consultorio',
            name='alias_consultorio',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='datos_personales',
            name='nombre',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='clave',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='colonia',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='cp',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='num_exterior',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='num_interior',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='dgp',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AlterField(
            model_name='facturacion_datos_doctor',
            name='razon_social',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AlterField(
            model_name='facturacion_datos_doctor',
            name='regimen_fiscal',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AlterField(
            model_name='facturacion_datos_doctor',
            name='tipo_comprobante',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AlterField(
            model_name='facturacion_datos_paciente',
            name='cfdi',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AlterField(
            model_name='facturacion_datos_paciente',
            name='num_req_id_fiscal',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='facturacion_datos_paciente',
            name='razon_social',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AlterField(
            model_name='facturacion_datos_paciente',
            name='residencia_fiscal',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='facturacion_datos_paciente',
            name='rfc_registrado',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='clave',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='indicaciones',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='antecedentes_principales',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='notas',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tipo_sangre',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='url_arch_priv',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AlterField(
            model_name='pago',
            name='forma_pago',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='lada',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='tipo',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
