# Generated by Django 2.1.7 on 2019-03-22 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0029_auto_20190322_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Datos_personales',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Datos_personales'),
        ),
    ]
