# Generated by Django 2.1.7 on 2019-03-22 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0030_auto_20190322_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Datos_personales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Datos_personales'),
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Telefono',
        ),
        migrations.AddField(
            model_name='doctor',
            name='Telefono',
            field=models.ManyToManyField(blank=True, null=True, to='dem.Telefono'),
        ),
    ]
