# Generated by Django 2.1.7 on 2019-03-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0031_auto_20190322_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistente',
            name='Telefono',
        ),
        migrations.AddField(
            model_name='asistente',
            name='Telefono',
            field=models.ManyToManyField(blank=True, null=True, to='dem.Telefono'),
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='Consulta_campos',
        ),
        migrations.AddField(
            model_name='consulta',
            name='Consulta_campos',
            field=models.ManyToManyField(blank=True, null=True, to='dem.Consulta_campos'),
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='Diagnostico',
        ),
        migrations.AddField(
            model_name='consulta',
            name='Diagnostico',
            field=models.ManyToManyField(blank=True, null=True, to='dem.Diagnostico'),
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='Estudio',
        ),
        migrations.AddField(
            model_name='consulta',
            name='Estudio',
            field=models.ManyToManyField(blank=True, null=True, to='dem.Estudio'),
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='Pago',
        ),
        migrations.AddField(
            model_name='consulta',
            name='Pago',
            field=models.ManyToManyField(blank=True, null=True, to='dem.Pago'),
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='Receta',
        ),
        migrations.AddField(
            model_name='consulta',
            name='Receta',
            field=models.ManyToManyField(blank=True, null=True, to='dem.Receta'),
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Asistente',
        ),
        migrations.AddField(
            model_name='doctor',
            name='Asistente',
            field=models.ManyToManyField(blank=True, null=True, to='dem.Asistente'),
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Consulta_campos_conf',
        ),
        migrations.AddField(
            model_name='doctor',
            name='Consulta_campos_conf',
            field=models.ManyToManyField(blank=True, null=True, to='dem.Consulta_campos_conf'),
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Consultorio',
        ),
        migrations.AddField(
            model_name='doctor',
            name='Consultorio',
            field=models.ManyToManyField(blank=True, null=True, to='dem.Consultorio'),
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Especialidad',
        ),
        migrations.AddField(
            model_name='doctor',
            name='Especialidad',
            field=models.ManyToManyField(blank=True, null=True, to='dem.Especialidad'),
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Expediente_conf',
        ),
        migrations.AddField(
            model_name='doctor',
            name='Expediente_conf',
            field=models.ManyToManyField(blank=True, null=True, to='dem.Expediente_conf'),
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Horario',
        ),
        migrations.AddField(
            model_name='doctor',
            name='Horario',
            field=models.ManyToManyField(blank=True, null=True, to='dem.Horario'),
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Paciente',
        ),
        migrations.AddField(
            model_name='doctor',
            name='Paciente',
            field=models.ManyToManyField(blank=True, null=True, to='dem.Paciente'),
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Servicio_externo',
        ),
        migrations.AddField(
            model_name='doctor',
            name='Servicio_externo',
            field=models.ManyToManyField(blank=True, null=True, to='dem.Servicio_externo'),
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='Receta',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='Receta',
            field=models.ManyToManyField(blank=True, null=True, to='dem.Receta'),
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='Acompañante',
        ),
        migrations.AddField(
            model_name='paciente',
            name='Acompañante',
            field=models.ManyToManyField(blank=True, null=True, to='dem.Acompañante'),
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='Alergia',
        ),
        migrations.AddField(
            model_name='paciente',
            name='Alergia',
            field=models.ManyToManyField(blank=True, null=True, to='dem.Alergia'),
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='Antecedentes',
        ),
        migrations.AddField(
            model_name='paciente',
            name='Antecedentes',
            field=models.ManyToManyField(blank=True, null=True, to='dem.Antecedentes'),
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='Consulta',
        ),
        migrations.AddField(
            model_name='paciente',
            name='Consulta',
            field=models.ManyToManyField(blank=True, null=True, to='dem.Consulta'),
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='Telefono',
        ),
        migrations.AddField(
            model_name='paciente',
            name='Telefono',
            field=models.ManyToManyField(blank=True, null=True, to='dem.Telefono'),
        ),
    ]
