# Generated by Django 2.1.7 on 2019-03-22 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0033_auto_20190322_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='Cita_externa',
        ),
        migrations.AddField(
            model_name='doctor',
            name='Cita_externa',
            field=models.ManyToManyField(null=True, to='dem.Cita_externa'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Facturacion_datos_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Facturacion_datos_doctor'),
        ),
    ]
