# Generated by Django 2.1.7 on 2019-03-22 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0036_auto_20190322_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='cantidad',
        ),
        migrations.AlterField(
            model_name='acompañante',
            name='relacion',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='alergia',
            name='alergia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='asistente',
            name='Telefono',
        ),
        migrations.AddField(
            model_name='asistente',
            name='Telefono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Telefono'),
        ),
        migrations.AlterField(
            model_name='asistente',
            name='permisos',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='cita_externa',
            name='color',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='cita_externa',
            name='estatus',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cita_externa',
            name='fecha_cita',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cita_externa',
            name='hora_final',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='cita_externa',
            name='hora_inicio',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='cita_externa',
            name='tipo',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='Consulta_campos',
        ),
        migrations.AddField(
            model_name='consulta',
            name='Consulta_campos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Consulta_campos'),
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='Diagnostico',
        ),
        migrations.AddField(
            model_name='consulta',
            name='Diagnostico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Diagnostico'),
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='Estudio',
        ),
        migrations.AddField(
            model_name='consulta',
            name='Estudio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Estudio'),
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='Pago',
        ),
        migrations.AddField(
            model_name='consulta',
            name='Pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Pago'),
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='Receta',
        ),
        migrations.AddField(
            model_name='consulta',
            name='Receta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Receta'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='consultorio',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='estatus',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='fecha_consulta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='hora',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='motivo_consulta',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='consulta_campos',
            name='nota',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='consulta_campos',
            name='sub_tipo',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='consulta_campos',
            name='tipo',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='consulta_campos',
            name='tipo_campo',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='consulta_campos',
            name='titulo',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='consulta_campos_conf',
            name='sub_tipo',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='consulta_campos_conf',
            name='tipo',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='consulta_campos_conf',
            name='tipo_campo',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='consulta_campos_conf',
            name='titulo',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='consultorio',
            name='nombre_consultorio',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='contraseña',
            name='Contraseña',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='datos_personales',
            name='correo',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='datos_personales',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datos_personales',
            name='nombre',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='datos_personales',
            name='rfc',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='datos_personales',
            name='sexo',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='datos_personales',
            name='url_foto',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='nombre_diagnostico',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='vigente',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='calle',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Asistente',
        ),
        migrations.AddField(
            model_name='doctor',
            name='Asistente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Asistente'),
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Cita_externa',
        ),
        migrations.AddField(
            model_name='doctor',
            name='Cita_externa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Cita_externa'),
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Consulta_campos_conf',
        ),
        migrations.AddField(
            model_name='doctor',
            name='Consulta_campos_conf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Consulta_campos_conf'),
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Consultorio',
        ),
        migrations.AddField(
            model_name='doctor',
            name='Consultorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Consultorio'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Datos_personales',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Datos_personales'),
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Especialidad',
        ),
        migrations.AddField(
            model_name='doctor',
            name='Especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Especialidad'),
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Expediente_conf',
        ),
        migrations.AddField(
            model_name='doctor',
            name='Expediente_conf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Expediente_conf'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Facturacion_datos_doctor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Facturacion_datos_doctor'),
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Horario',
        ),
        migrations.AddField(
            model_name='doctor',
            name='Horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Horario'),
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Paciente',
        ),
        migrations.AddField(
            model_name='doctor',
            name='Paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Paciente'),
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Servicio_externo',
        ),
        migrations.AddField(
            model_name='doctor',
            name='Servicio_externo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Servicio_externo'),
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Telefono',
        ),
        migrations.AddField(
            model_name='doctor',
            name='Telefono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Telefono'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='cedula',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='nombre_especialidad',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='fecha_estudios',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='nombre_carpeta',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='url_archivo',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='nota',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='sub_tipo',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='tipo',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='tipo_campo',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='titulo',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='expediente_conf',
            name='sub_tipo',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='expediente_conf',
            name='tipo',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='expediente_conf',
            name='tipo_campo',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='expediente_conf',
            name='titulo',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='facturacion_datos_doctor',
            name='rfc',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='facturacion_datos_paciente',
            name='rfc',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='dia',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora_final',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora_inicio',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='Receta',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='Receta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Receta'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='Acompañante',
        ),
        migrations.AddField(
            model_name='paciente',
            name='Acompañante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Acompañante'),
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='Alergia',
        ),
        migrations.AddField(
            model_name='paciente',
            name='Alergia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Alergia'),
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='Antecedentes',
        ),
        migrations.AddField(
            model_name='paciente',
            name='Antecedentes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Antecedentes'),
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='Consulta',
        ),
        migrations.AddField(
            model_name='paciente',
            name='Consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Consulta'),
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='Telefono',
        ),
        migrations.AddField(
            model_name='paciente',
            name='Telefono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Telefono'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='descripcion_pago',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='factura_pago',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='fecha_receta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='folio_receta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='servicio_externo',
            name='descripcion_servicio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
