# Generated by Django 2.1.7 on 2019-03-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0041_auto_20190325_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='nombre',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
