# Generated by Django 2.1.7 on 2019-03-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0043_auto_20190325_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistente',
            name='estado',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='asistente',
            name='municipio',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='consultorio',
            name='calle',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='consultorio',
            name='colonia',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='consultorio',
            name='cp',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='consultorio',
            name='estado',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='consultorio',
            name='municipio',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='consultorio',
            name='num_exterior',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='consultorio',
            name='num_interior',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='estado',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='municipio',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='estado',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='municipio',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
