# Generated by Django 2.1.7 on 2019-03-27 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0046_auto_20190327_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='Paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dem.Paciente'),
        ),
    ]
