# Generated by Django 2.1.7 on 2019-03-27 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0052_auto_20190327_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudio',
            old_name='fecha_estudios',
            new_name='fecha_estudio',
        ),
    ]
