# Generated by Django 2.1.7 on 2019-03-27 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0058_auto_20190327_2217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acompañante',
            options={'verbose_name_plural': 'Acompañantes'},
        ),
        migrations.AlterModelOptions(
            name='alergia',
            options={'verbose_name_plural': 'Alergias'},
        ),
        migrations.AlterModelOptions(
            name='antecedentes',
            options={'verbose_name_plural': 'Antecedentes'},
        ),
        migrations.AlterModelOptions(
            name='asistente',
            options={'verbose_name_plural': 'Asistentes'},
        ),
        migrations.AlterModelOptions(
            name='cita_externa',
            options={'verbose_name_plural': 'Citas Externas'},
        ),
        migrations.AlterModelOptions(
            name='consulta',
            options={'verbose_name_plural': 'Consultas'},
        ),
        migrations.AlterModelOptions(
            name='consultorio',
            options={'verbose_name_plural': 'Consultorios'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name_plural': 'Doctores'},
        ),
        migrations.AlterModelOptions(
            name='especialidad',
            options={'verbose_name_plural': 'Especialidades'},
        ),
        migrations.AlterModelOptions(
            name='facturacion_datos_doctor',
            options={'verbose_name_plural': 'Doctor - Datos de facturación'},
        ),
        migrations.AlterModelOptions(
            name='facturacion_datos_paciente',
            options={'verbose_name_plural': 'Paciente - Datos de Facturación'},
        ),
        migrations.AlterModelOptions(
            name='horario',
            options={'verbose_name_plural': 'Horarios'},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterModelOptions(
            name='telefono_acompañante',
            options={'verbose_name_plural': 'Acompañantes - Telefonos'},
        ),
        migrations.AlterModelOptions(
            name='telefono_asistente',
            options={'verbose_name_plural': 'Asistentes - Telefonos'},
        ),
        migrations.AlterModelOptions(
            name='telefono_doctor',
            options={'verbose_name_plural': 'Doctores - Telefonos'},
        ),
        migrations.AlterModelOptions(
            name='telefono_paciente',
            options={'verbose_name_plural': 'Pacientes - Telefonos'},
        ),
    ]
