# Generated by Django 2.1.7 on 2019-03-28 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0062_auto_20190328_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='Doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dem.Doctor'),
        ),
    ]
